services:

  incredible_bulk_api:
    build:
      context: .
      target: production
    expose:
      - 8000
    volumes:
      - logs:/var/log
      - static_json_gzip:/app/static_json_gzip
    depends_on:
      - image_preview_api

  image_preview_api:
    build:
      context: imagePreviewAPI/
    expose:
      - 8000
    volumes:
      - logs:/var/log

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - incredible_bulk_api
    working_dir: /usr/share/nginx/html/
    volumes:
      - logs:/var/log
      #- static_json_gzip:/app/static_json_gzip
      - ./static_json_gzip:/app/static_json_gzip
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
    logs:
    static_json_gzip:
