services:

  incredible_bulk_api:
    build:
      context: .
      target: production
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - _generated:/app/_generated
      - persistent_cache:/app/__cache
    depends_on:
      - image_preview_api

  image_preview_api:
    build:
      context: imagePreviewAPI/
    expose:
      - 8000
    ports:
      - 8001:8000

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - incredible_bulk_api
    working_dir: /usr/share/nginx/html/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - logs:/var/log
      - _generated:/app/_generated


volumes:
    logs:
    persistent_cache:
    _generated:
