services:

  incredibleBulkAPI:
    build:
      context: .
    expose:
      - 8000
    volumes:
      - _generated:/app/_generated

  nginx:
    build:
      context: nginx/
    ports:
      - 80:80
    links:
      - incredibleBulkAPI
    volumes:
      - logs:/var/log
      - _generated:/app/_generated

volumes:
    logs:
    _generated:
